.Dd $Mdocdate$
.Dt mario 1
.Os
.Sh NAME
.Nm mario
.Nd a plumber
.Sh SYNOPSIS
.Nm mario
.Op Ar options
.Ar MSG
.Ao raw, url Ac
.Sh DESCRIPTION
The
.Nm
is a powerful plumber.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl Fl config Pa FILE
Configuration file to use.
.It Fl Fl guess
Guess the kind of the message.
.It Fl h Fl Fl help
Display the help message and quit.
.It Fl Fl rule Pa FILE
Rules file to use.
.It Fl v Fl Fl verbose
Increase the configured verbosity level by one. Specify
multiple times to increase log level multiple times.
.El
.Sh ENVIRONMENT
.Bl -tag -width indent
.It Ev BROWSER
#TODO
.It Ev EDITOR
#TODO
.El
.Sh FILES
.Bl -tag -width indent
.It Pa $XDG_CONFIG_HOME/mario/config
Global configuration file for mario.
.It Pa $XDG_CONFIG_HOME/mario/config
Default rules file for mario.
.El
.Sh EXIT STATUS
.Nm
exits 0 if a rule successfully matches and  all  actions
run successfully execute, and >0 if an error occurs.
.Sh EXAMPLES
.Bl -tag -width indent
.It A simple example using an URL as the message:
.Nm
.Ar http://www.example.org/ Ar url
.El
.Sh SEE ALSO
.Xr mario.plumb 5 ,
.Xr mario.config 5
.Sh HISTORY
.Nm
was inspired by the Plan 9 utility
.Sy plumb
and the matching
file server
.Sy plumber .
.Sh AUTHORS
Damir Jelić, Denis Kasak
